name:  OpenDevOps-Maria
description: |
   maria Image for Open DevOps Pipeline
version:  1.0.0
category:  COM
maintainer:  open.devops
license:  Apache 2
projectURL: https://github.com/ open-devops/docker-com-maria
